#!/usr/bin/env bash
#
# open-combined-pr.sh — Ask Claude to write the PR body from the structured
# sync logs, then open the PR via the gh CLI.
#
# Environment:
#   GH_TOKEN           - GitHub token (from App)
#   ANTHROPIC_API_KEY  - for Claude CLI
#   ANDROID_OUTPUT     - path to claude-output-android.json (may not exist)
#   IOS_OUTPUT         - path to claude-output-ios.json (may not exist)
#   ANDROID_MODULE / ANDROID_VERSION
#   IOS_MODULE / IOS_VERSION
#   RELEASE_NAME / BRANCH
#   WRAPPER            - wrapper name for the PR title (default: wrapper)
#   MODEL              - Claude model (default sonnet-4-6)
#   TOOLING_ROOT       - path to the tooling repo checkout (default: $GITHUB_WORKSPACE/tooling)

set -uo pipefail

MODEL="${MODEL:-sonnet-4-6}"
TOOLING_ROOT="${TOOLING_ROOT:-${GITHUB_WORKSPACE}/tooling}"
WRAPPER="${WRAPPER:-wrapper}"
BASE_REF="${BASE_REF:-develop}"

# Build PR title
title="task: sync ${WRAPPER} with native release ${RELEASE_NAME}"
if [ -n "${ANDROID_VERSION:-}" ] && [ -n "${IOS_VERSION:-}" ]; then
    title="task: sync ${WRAPPER} ← Android ${ANDROID_MODULE}v${ANDROID_VERSION} + iOS ${IOS_VERSION} (${RELEASE_NAME})"
elif [ -n "${ANDROID_VERSION:-}" ]; then
    title="task: sync ${WRAPPER} ← Android ${ANDROID_MODULE}v${ANDROID_VERSION} (${RELEASE_NAME})"
elif [ -n "${IOS_VERSION:-}" ]; then
    title="task: sync ${WRAPPER} ← iOS ${IOS_VERSION} (${RELEASE_NAME})"
fi

# Ask Claude to generate the PR body from the structured logs.
export WRAPPER ANDROID_MODULE ANDROID_VERSION IOS_MODULE IOS_VERSION RELEASE_NAME BRANCH

prompt="$(envsubst < "${TOOLING_ROOT}/prompts/pr-description.md")"

# Append the raw sync logs to the prompt so Claude doesn't need to read files
# outside its working directory (the JSON envelopes live at the workspace root,
# while this runs from the wrapper checkout). Appended AFTER envsubst so the
# JSON's own `$` characters aren't mangled.
android_log="$(cat "${ANDROID_OUTPUT}" 2>/dev/null || true)"
ios_log="$(cat "${IOS_OUTPUT}" 2>/dev/null || true)"
prompt="${prompt}

=== BEGIN android sync log (claude-output-android.json) ===
${android_log}
=== END android sync log ===

=== BEGIN ios sync log (claude-output-ios.json) ===
${ios_log}
=== END ios sync log ==="

body=$(claude -p "$prompt" --model "$MODEL")

# Defensive: strip any preamble before the first Markdown H2 (Claude sometimes
# prepends "Here's the PR description:" etc.). Keep from the first "## " onward.
cleaned="$(printf '%s\n' "$body" | sed -n '/^## /,$p')"
[ -n "$cleaned" ] && body="$cleaned"

if [ -z "$body" ]; then
    echo "::warning::Claude returned an empty PR body. Falling back to a minimal description."
    body=$(cat <<EOF
🤖 Auto-generated by clevertap-wrapper-sync.

Android: ${ANDROID_MODULE:-—} ${ANDROID_VERSION:-—}
iOS: ${IOS_MODULE:-—} ${IOS_VERSION:-—}

Sync logs failed to render. See workflow artifacts for raw outputs.
EOF
)
fi

# Decide labels based on what was synced
labels="auto-generated"
if jq -e '.build_propagated[] | select(.change | test("minSdk|deployment_target"))' "${ANDROID_OUTPUT:-/dev/null}" "${IOS_OUTPUT:-/dev/null}" 2>/dev/null | head -1 | grep -q .; then
    labels="${labels},breaking-change"
fi
if jq -e '.surfaced | length > 0' "${ANDROID_OUTPUT:-/dev/null}" 2>/dev/null | grep -q true \
   || jq -e '.surfaced | length > 0' "${IOS_OUTPUT:-/dev/null}" 2>/dev/null | grep -q true; then
    labels="${labels},new-api"
else
    labels="${labels},bug-fix-only"
fi

# If either post-sync build failed, flag the PR so reviewers know to expect
# red CI. ANDROID_BUILD_OUTCOME / IOS_BUILD_OUTCOME are step outcomes passed
# from the workflow ("success", "failure", "skipped", or empty if the step
# didn't run).
if [ "${ANDROID_BUILD_OUTCOME:-}" = "failure" ] || [ "${IOS_BUILD_OUTCOME:-}" = "failure" ]; then
    labels="${labels},build-failed"
    # Also prepend a clear marker to the PR body so it's visible at a glance.
    body="> ⚠️ **Post-sync build failed.** Claude's edits compile-failed on one or both platforms. The PR is open anyway — pull the branch locally, fix the build, push. Check the workflow logs for the specific error.

$body"
fi

# Ensure the labels we want to use actually exist on the repo. `gh label
# create --force` creates them if missing or updates color/desc if present
# — idempotent. Without this, `gh pr create --label X` fails if X doesn't
# exist on the repo (common for fresh forks). Colors are GitHub's standard
# hex (without #).
#
# Parallel arrays (not associative arrays) on purpose: bash with `set -u`
# treats keys containing `-` as parameter expansion (e.g.
# ${arr[auto-generated]} → looks for $auto and bails). Integer indices
# don't have that problem.
LABEL_NAMES=(auto-generated bug-fix-only new-api breaking-change build-failed)
LABEL_COLORS=(ededed         0e8a16       1d76db  b60205          d93f0b)
for i in "${!LABEL_NAMES[@]}"; do
    name="${LABEL_NAMES[$i]}"
    color="${LABEL_COLORS[$i]}"
    gh label create "$name" --color "$color" --force 2>/dev/null \
        || echo "::warning::could not ensure label '$name' (may be a permissions issue; continuing)"
done

# Open the PR. If --label fails, retry without labels so we at least get
# the PR opened (labels can be added after the fact via gh pr edit).
if ! gh pr create \
        --base "${BASE_REF}" \
        --head "${BRANCH}" \
        --title "$title" \
        --body "$body" \
        --label "$labels"; then
    echo "::warning::PR create with labels failed; retrying without labels."
    if ! gh pr create \
            --base "${BASE_REF}" \
            --head "${BRANCH}" \
            --title "$title" \
            --body "$body"; then
        echo "::error::Failed to open PR even without labels. The branch may already have an open PR."
        exit 1
    fi
    # PR opened sans labels — try to add them individually so a single missing
    # label doesn't tank the rest.
    pr_number=$(gh pr list --head "${BRANCH}" --json number --jq '.[0].number')
    if [ -n "$pr_number" ]; then
        for label in ${labels//,/ }; do
            gh pr edit "$pr_number" --add-label "$label" 2>/dev/null \
                || echo "::warning::could not add label '$label' to PR #$pr_number"
        done
    fi
fi

echo "✅ PR opened against develop from ${BRANCH}"
