#!/usr/bin/env bash
#
# open-combined-pr.sh — Ask Claude to write the PR body from the structured
# sync logs, then open the PR via the gh CLI.
#
# Environment:
#   GH_TOKEN           - GitHub token (from App)
#   ANTHROPIC_API_KEY  - for Claude CLI
#   ANDROID_OUTPUT     - path to claude-output-android.json (may not exist)
#   IOS_OUTPUT         - path to claude-output-ios.json (may not exist)
#   ANDROID_MODULE / ANDROID_VERSION
#   IOS_MODULE / IOS_VERSION
#   RELEASE_NAME / BRANCH
#   MODEL              - Claude model (default sonnet-4-6)
#   TOOLING_ROOT       - path to the tooling repo checkout (default: $GITHUB_WORKSPACE/tooling)

set -uo pipefail

MODEL="${MODEL:-sonnet-4-6}"
TOOLING_ROOT="${TOOLING_ROOT:-${GITHUB_WORKSPACE}/tooling}"

# Build PR title
title="task: sync wrapper with native release ${RELEASE_NAME}"
if [ -n "${ANDROID_VERSION:-}" ] && [ -n "${IOS_VERSION:-}" ]; then
    title="task: sync RN ← Android ${ANDROID_MODULE}v${ANDROID_VERSION} + iOS ${IOS_VERSION} (${RELEASE_NAME})"
elif [ -n "${ANDROID_VERSION:-}" ]; then
    title="task: sync RN ← Android ${ANDROID_MODULE}v${ANDROID_VERSION} (${RELEASE_NAME})"
elif [ -n "${IOS_VERSION:-}" ]; then
    title="task: sync RN ← iOS ${IOS_VERSION} (${RELEASE_NAME})"
fi

# Ask Claude to generate the PR body from the structured logs
export ANDROID_OUTPUT IOS_OUTPUT ANDROID_MODULE ANDROID_VERSION IOS_MODULE IOS_VERSION RELEASE_NAME BRANCH

prompt="$(envsubst < "${TOOLING_ROOT}/prompts/pr-description.md")"
body=$(claude -p "$prompt" --model "$MODEL")

if [ -z "$body" ]; then
    echo "::warning::Claude returned an empty PR body. Falling back to a minimal description."
    body=$(cat <<EOF
🤖 Auto-generated by clevertap-wrapper-sync.

Android: ${ANDROID_MODULE:-—} ${ANDROID_VERSION:-—}
iOS: ${IOS_MODULE:-—} ${IOS_VERSION:-—}

Sync logs failed to render. See workflow artifacts for raw outputs.
EOF
)
fi

# Decide labels based on what was synced
labels="auto-generated"
if jq -e '.build_propagated[] | select(.change | test("minSdk|deployment_target"))' "${ANDROID_OUTPUT:-/dev/null}" "${IOS_OUTPUT:-/dev/null}" 2>/dev/null | head -1 | grep -q .; then
    labels="${labels},breaking-change"
fi
if jq -e '.surfaced | length > 0' "${ANDROID_OUTPUT:-/dev/null}" 2>/dev/null | grep -q true \
   || jq -e '.surfaced | length > 0' "${IOS_OUTPUT:-/dev/null}" 2>/dev/null | grep -q true; then
    labels="${labels},new-api"
else
    labels="${labels},bug-fix-only"
fi

# If either post-sync build failed, flag the PR so reviewers know to expect
# red CI. ANDROID_BUILD_OUTCOME / IOS_BUILD_OUTCOME are step outcomes passed
# from the workflow ("success", "failure", "skipped", or empty if the step
# didn't run).
if [ "${ANDROID_BUILD_OUTCOME:-}" = "failure" ] || [ "${IOS_BUILD_OUTCOME:-}" = "failure" ]; then
    labels="${labels},build-failed"
    # Also prepend a clear marker to the PR body so it's visible at a glance.
    body="> ⚠️ **Post-sync build failed.** Claude's edits compile-failed on one or both platforms. The PR is open anyway — pull the branch locally, fix the build, push. Check the workflow logs for the specific error.

$body"
fi

# Open the PR
gh pr create \
    --base develop \
    --head "${BRANCH}" \
    --title "$title" \
    --body "$body" \
    --label "$labels" || {
        echo "::error::Failed to open PR. The branch may already have an open PR."
        exit 1
    }

echo "✅ PR opened against develop from ${BRANCH}"
