#!/usr/bin/env bash
#
# open-combined-pr.sh — Ask Claude to write the PR body from the structured
# sync logs, then open the PR via the gh CLI.
#
# Environment:
#   GH_TOKEN           - GitHub token (from App)
#   ANTHROPIC_API_KEY  - for Claude CLI
#   ANDROID_OUTPUT     - path to claude-output-android.json (may not exist)
#   IOS_OUTPUT         - path to claude-output-ios.json (may not exist)
#   ANDROID_MODULE / ANDROID_VERSION
#   IOS_MODULE / IOS_VERSION
#   RELEASE_NAME / BRANCH
#   WRAPPER            - wrapper name for the PR title (default: wrapper)
#   MODEL              - Claude model (default sonnet-4-6)
#   TOOLING_ROOT       - path to the tooling repo checkout (default: $GITHUB_WORKSPACE/tooling)

set -uo pipefail

MODEL="${MODEL:-sonnet-4-6}"
TOOLING_ROOT="${TOOLING_ROOT:-${GITHUB_WORKSPACE}/tooling}"
WRAPPER="${WRAPPER:-wrapper}"
BASE_REF="${BASE_REF:-develop}"

# Build PR title
title="task: sync ${WRAPPER} with native release ${RELEASE_NAME}"
if [ "${WRAPPER}" = "expo" ]; then
    title="task: sync expo ← clevertap-react-native v${CLEVERTAP_RN_VERSION:-?} + Expo SDK ${EXPO_SDK_VERSION:-?} (${RELEASE_NAME})"
elif [ -n "${ANDROID_VERSION:-}" ] && [ -n "${IOS_VERSION:-}" ]; then
    title="task: sync ${WRAPPER} ← Android ${ANDROID_MODULE}v${ANDROID_VERSION} + iOS ${IOS_VERSION} (${RELEASE_NAME})"
elif [ -n "${ANDROID_VERSION:-}" ]; then
    title="task: sync ${WRAPPER} ← Android ${ANDROID_MODULE}v${ANDROID_VERSION} (${RELEASE_NAME})"
elif [ -n "${IOS_VERSION:-}" ]; then
    title="task: sync ${WRAPPER} ← iOS ${IOS_VERSION} (${RELEASE_NAME})"
fi

# Ask Claude to generate the PR body from the structured logs. Expo has a
# different output schema (version_bumps / integration_steps_changed rather than
# surfaced methods) so it uses its own PR-body prompt.
export WRAPPER ANDROID_MODULE ANDROID_VERSION IOS_MODULE IOS_VERSION RELEASE_NAME BRANCH
export CLEVERTAP_RN_VERSION EXPO_SDK_VERSION

if [ "${WRAPPER}" = "expo" ]; then
    prompt="$(envsubst < "${TOOLING_ROOT}/prompts/pr-description-expo.md")"
    expo_log="$(cat "${EXPO_OUTPUT}" 2>/dev/null || true)"
    prompt="${prompt}

=== BEGIN expo sync log (claude-output-expo.json) ===
${expo_log}
=== END expo sync log ==="
else
    prompt="$(envsubst < "${TOOLING_ROOT}/prompts/pr-description.md")"
    # Append the raw sync logs to the prompt so Claude doesn't need to read files
    # outside its working directory (the JSON envelopes live at the workspace root,
    # while this runs from the wrapper checkout). Appended AFTER envsubst so the
    # JSON's own `$` characters aren't mangled.
    android_log="$(cat "${ANDROID_OUTPUT}" 2>/dev/null || true)"
    ios_log="$(cat "${IOS_OUTPUT}" 2>/dev/null || true)"
    prompt="${prompt}

=== BEGIN android sync log (claude-output-android.json) ===
${android_log}
=== END android sync log ===

=== BEGIN ios sync log (claude-output-ios.json) ===
${ios_log}
=== END ios sync log ==="
fi

body=$(claude -p "$prompt" --model "$MODEL")

# Defensive: strip any preamble before the first Markdown H2 (Claude sometimes
# prepends "Here's the PR description:" etc.). Keep from the first "## " onward.
cleaned="$(printf '%s\n' "$body" | sed -n '/^## /,$p')"
[ -n "$cleaned" ] && body="$cleaned"

if [ -z "$body" ]; then
    echo "::warning::Claude returned an empty PR body. Falling back to a minimal description."
    body=$(cat <<EOF
🤖 Auto-generated by clevertap-wrapper-sync.

Android: ${ANDROID_MODULE:-—} ${ANDROID_VERSION:-—}
iOS: ${IOS_MODULE:-—} ${IOS_VERSION:-—}

Sync logs failed to render. See workflow artifacts for raw outputs.
EOF
)
fi

# Decide labels based on what was synced. The structured log lives inside the
# CLI envelope's `.result` string, so we parse it with `fromjson?` (tolerates a
# non-JSON result by yielding nothing → safe defaults).
labels="auto-generated"
if [ "${WRAPPER}" = "expo" ]; then
    # Expo has no `surfaced` methods — derive labels from version_bumps /
    # integration_steps_changed, and breaking-change from a major bump (or a
    # propagated minSdk/deployment-target change). The structured log lives inside
    # the envelope's `.result` as text that may be fenced/prose-wrapped, so a plain
    # `fromjson` fails — extract the {...} block first, then parse that.
    expo_struct=$(jq -r '.result // ""' "${EXPO_OUTPUT:-/dev/null}" 2>/dev/null \
        | python3 -c "import sys,re; t=sys.stdin.read(); m=re.search(r'\{.*\}', t, re.DOTALL); sys.stdout.write(m.group(0) if m else '{}')" 2>/dev/null || echo '{}')
    bump=$(printf '%s' "$expo_struct" | jq -r '.version_bump.bump_type // empty' 2>/dev/null || true)
    nchanges=$(printf '%s' "$expo_struct" | jq -r '((.version_bumps // []) | length) + ((.integration_steps_changed // []) | length)' 2>/dev/null || echo 0)
    breaking=$(printf '%s' "$expo_struct" | jq -r 'any((.build_propagated // [])[]; (.change // "") | test("minSdk|deployment_target"))' 2>/dev/null || echo false)
    if [ "$bump" = "major" ] || [ "$breaking" = "true" ]; then
        labels="${labels},breaking-change"
    fi
    if [ "${nchanges:-0}" -gt 0 ] 2>/dev/null; then
        labels="${labels},new-api"
    else
        labels="${labels},bug-fix-only"
    fi
else
    if jq -e '.build_propagated[] | select(.change | test("minSdk|deployment_target"))' "${ANDROID_OUTPUT:-/dev/null}" "${IOS_OUTPUT:-/dev/null}" 2>/dev/null | head -1 | grep -q .; then
        labels="${labels},breaking-change"
    fi
    if jq -e '.surfaced | length > 0' "${ANDROID_OUTPUT:-/dev/null}" 2>/dev/null | grep -q true \
       || jq -e '.surfaced | length > 0' "${IOS_OUTPUT:-/dev/null}" 2>/dev/null | grep -q true; then
        labels="${labels},new-api"
    else
        labels="${labels},bug-fix-only"
    fi
fi

# If either post-sync build failed, flag the PR so reviewers know to expect
# red CI. ANDROID_BUILD_OUTCOME / IOS_BUILD_OUTCOME are step outcomes passed
# from the workflow ("success", "failure", "skipped", or empty if the step
# didn't run).
if [ "${ANDROID_BUILD_OUTCOME:-}" = "failure" ] || [ "${IOS_BUILD_OUTCOME:-}" = "failure" ]; then
    labels="${labels},build-failed"
    # Also prepend a clear marker to the PR body so it's visible at a glance.
    body="> ⚠️ **Post-sync build failed.** Claude's edits compile-failed on one or both platforms. The PR is open anyway — pull the branch locally, fix the build, push. Check the workflow logs for the specific error.

$body"
fi

# Deterministic completeness check (model-independent): a sync that opened a PR
# should have updated the CHANGELOG and the wrapper's canonical version file. If
# those aren't in the committed diff, the run likely stopped before finishing
# (the version-bump / changelog tail steps). Flag it — non-blocking — so a
# reviewer completes it rather than silently shipping a half-done sync.
case "${WRAPPER}" in
    flutter)       version_file="pubspec.yaml" ;;
    react-native)  version_file="package.json" ;;
    expo)          version_file="package.json" ;;
    *)             version_file="" ;;
esac
changed="$(git diff --name-only "origin/${BASE_REF}...HEAD" 2>/dev/null || git show --name-only --format= HEAD 2>/dev/null)"
missing=""
printf '%s\n' "$changed" | grep -qx "CHANGELOG.md" || missing="${missing} CHANGELOG.md"
if [ -n "$version_file" ]; then
    printf '%s\n' "$changed" | grep -qx "$version_file" || missing="${missing} ${version_file}"
fi
if [ -n "$missing" ]; then
    labels="${labels},incomplete-sync"
    body="> ⚠️ **Incomplete sync — expected files were NOT updated:**${missing}. The sync likely stopped before finishing the version bump / changelog. Review and complete these before merge.

$body"
fi

# Ensure the labels we want to use actually exist on the repo. `gh label
# create --force` creates them if missing or updates color/desc if present
# — idempotent. Without this, `gh pr create --label X` fails if X doesn't
# exist on the repo (common for fresh forks). Colors are GitHub's standard
# hex (without #).
#
# Parallel arrays (not associative arrays) on purpose: bash with `set -u`
# treats keys containing `-` as parameter expansion (e.g.
# ${arr[auto-generated]} → looks for $auto and bails). Integer indices
# don't have that problem.
LABEL_NAMES=(auto-generated bug-fix-only new-api breaking-change build-failed incomplete-sync)
LABEL_COLORS=(ededed         0e8a16       1d76db  b60205          d93f0b       e99695)
for i in "${!LABEL_NAMES[@]}"; do
    name="${LABEL_NAMES[$i]}"
    color="${LABEL_COLORS[$i]}"
    gh label create "$name" --color "$color" --force 2>/dev/null \
        || echo "::warning::could not ensure label '$name' (may be a permissions issue; continuing)"
done

# Open the PR. If --label fails, retry without labels so we at least get
# the PR opened (labels can be added after the fact via gh pr edit).
if ! gh pr create \
        --base "${BASE_REF}" \
        --head "${BRANCH}" \
        --title "$title" \
        --body "$body" \
        --label "$labels"; then
    echo "::warning::PR create with labels failed; retrying without labels."
    if ! gh pr create \
            --base "${BASE_REF}" \
            --head "${BRANCH}" \
            --title "$title" \
            --body "$body"; then
        echo "::error::Failed to open PR even without labels. The branch may already have an open PR."
        exit 1
    fi
    # PR opened sans labels — try to add them individually so a single missing
    # label doesn't tank the rest.
    pr_number=$(gh pr list --head "${BRANCH}" --json number --jq '.[0].number')
    if [ -n "$pr_number" ]; then
        for label in ${labels//,/ }; do
            gh pr edit "$pr_number" --add-label "$label" 2>/dev/null \
                || echo "::warning::could not add label '$label' to PR #$pr_number"
        done
    fi
fi

echo "✅ PR opened against develop from ${BRANCH}"
